spring:
  application:
    name: oauth2-demo-fb-spring-boot
security:
  oauth2:
    client:
      clientId: 664314521731682
      clientSecret: 82c00d3e293cbd535a9578b45752e33c
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me